var langArr = {
    "en": {
        "professional_account_type": "Account Type",
        "professional_account_type_2": "Your current account type is professional account. ",
        "professional_account_type_3": "Your current account type is standard account. <br />Please note, if you meet the requirements for Mitrade Pro, you can upgrade your account to a professional account. ",
        "account_type_difference_title": "Mitrade Pro VS Our Standard Account",
        "professional_account_table_title_1": "Leverage (up to) and other account spec",
        "standard_account_title": "Standard Account <br><span>(Until 28th Mar 2021)</span>",
        "standard_account_title_2": "Standard Account <br><span>(From 29th Mar 2021 onwards)</span>",
        "professional_account_title": "Mitrade Pro",
        "professional_account_table_forex": "Forex",
        "professional_account_table_indices": "Indices",
        "professional_account_table_gold": "Gold",
        "professional_account_table_commodities": "Commodities (other than gold)",
        "professional_account_table_share": "Shares",
        "professional_account_table_7": "Exclusive Market Analysis",
        "professional_account_table_8": "TProfessional TradingView Charts",
        "professional_account_table_9": "Free Economic Calendar & News",
        "professional_account_table_10": "Negative Balance Protection",
        "professional_account_table_11": "Trailing Stop Loss",
        "professional_account_table_12": "Product Disclosure Statement & Financial Services Guide",
        "professional_account_table_list2_2": "Major Pairs*<br/>1:30<br />Minor Pairs**<br/>1:20",
        "professional_account_table_list2_3": "Major Indices^<br/>1:20<br />Minor Indices^^<br/>1:10",
        "professional_account_major_currency": "*Major Pairs:",
        "professional_account_major_currency_desc": "a pair of currencies that consists of any two of the following: AUD, GBP, CAD, EUR, JPY, CHF and USD",
        "professional_account_ordinary_currency": "**Minor Pairs:",
        "professional_account_ordinary_currency_desc": "any pair that is not Major Pair",
        "professional_account_major_indices": "^Major Indices: ",
        "professional_account_ordinary_indices": "^^Minor Indices: ",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 and AUS200",
        "professional_account_ordinaryr_indices_desc": "a stock market index that is not a major stock market index.",
        "professional_account_apply_requirements": "How to Apply for Mitrade Pro?",
        "professional_account_apply_requirements_desc": "By satisfying one of the conditions below, you are qualified to apply for Mitrade Pro:",
        "professional_account_apply_requirements_1": "Asset: <br />Have net asset* of at least <span>AU$2.5 million</span>.",
        "professional_account_apply_requirements_2": "Income: <br />Gross income for each of the last two financial years was at least <span>AU$250,000</span>",
        "professional_account_certificate": "You will need to supply an accountancy certificate** to prove that you have met the above criteria. Template for the accountancy certificate can be found <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>here</a>.",
        "professional_account_net_asset": "*Net assets",
        "professional_account_net_asset_desc": "Refer to the total worth of assets such as your property, car, savings, shares and other investments.",
        "professional_account_net_asset_desc_2": "**Accountancy certificate must be prepared by a member of the CPA Australia/Chartered Accountants Australia.",
        "professional_account_net_asset_desc_3": "If you are qualify for Mitrade Pro, please kindly send your accountancy certification to cs@mitrade.com and we will take care of the rest for you.",
        "professional_account_faq": "More questions >"
    },
    "cn": {
        "professional_account_type": "账户类型",
        "professional_account_type_2": "您当前的账户类型为专业账户。",
        "professional_account_type_3": "您当前的账户类型为标准交易账户。<br />请知悉，若您满足所需条件，您可以申请将账户升级为专业账户。",
        "account_type_difference_title": "专业账户与标准账户有何不同？",
        "professional_account_table_title_1": "最⾼杠杆及其他账户项⽬",
        "standard_account_title": "标准账户<br><span>(直⾄<br>2021年3⽉28⽇)</span>",
        "standard_account_title_2": "标准账户<br><span>(自2021年<br>3月29日起适用)</span>",
        "professional_account_title": "专业账户",
        "professional_account_table_forex": "外汇",
        "professional_account_table_indices": "指数",
        "professional_account_table_gold": "黄金",
        "professional_account_table_commodities": "大宗商品（黄金除外）",
        "professional_account_table_share": "股票",
        "professional_account_table_7": "独家市场分析",
        "professional_account_table_8": "TradingView 专业图表",
        "professional_account_table_9": "免费财经日历及新闻资讯",
        "professional_account_table_10": "负数额馀保护",
        "professional_account_table_11": "追踪⽌损功能",
        "professional_account_table_12": "产品披露声明及⾦融服务指南",
        "professional_account_table_list2_2": "主要货币对*<br/>1:30<br />次要货币对**<br/>1:20",
        "professional_account_table_list2_3": "主要指数^<br/>1:20<br />次要指数^^<br/>1:10",
        "professional_account_major_currency": "*主要货币对：",
        "professional_account_major_currency_desc": "包含以下任何两个货币的货币对：澳元、英镑、加元、欧元、⽇元、瑞郎及美元",
        "professional_account_ordinary_currency": "**次要货币对：",
        "professional_account_ordinary_currency_desc": "任何不是主要货币对的货币对",
        "professional_account_major_indices": "^主要指数：",
        "professional_account_ordinary_indices": "^^次要指数：",
        "professional_account_major_indices_desc": "法国40指数、德国30指数、美国30指数、欧洲50指数、英国100指数、美国科技股100指数、⽇本225指数、美国500指数及澳洲200指数",
        "professional_account_ordinaryr_indices_desc": "任何不是主要指数的指数",
        "professional_account_apply_requirements": "Mitrade 专业账户申请条件",
        "professional_account_apply_requirements_desc": "您仅需满足以下两个条件其中之一，即可申请将标准交易账户升级为专业账户：",
        "professional_account_apply_requirements_1": "资产：<br />持有最少 <span>250万澳元</span> 的净资产*",
        "professional_account_apply_requirements_2": "收入：<br />最近两个财政年中，年度总收⼊不少于 <span>25万澳元</span>",
        "professional_account_certificate": "您将需要提供相关会计证明**，以证明您已满足以上的申请资格。请使用我们提供的<a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>会计证明模板</a>。",
        "professional_account_net_asset": "*净资产：",
        "professional_account_net_asset_desc": "指您所有资产的总价值，包括您的房产、汽车、储蓄、股票及其他投资。",
        "professional_account_net_asset_desc_2": "**会计证明需由澳洲会计师公会会员（CPA Australia）或澳洲特许会计师协会会员（Chartered Accountants Australia）提供。",
        "professional_account_net_asset_desc_3": "如果您满足申请专业账户的资格，烦请您将相关会计证明发送至 cs@mitrade.com，我们将尽快为您完成剩下的申请手续。",
        "professional_account_faq": "更多疑问>"
    },
    "zh": {
        "professional_account_type": "賬戶類型",
        "professional_account_type_2": "您當前的賬戶類型為專業賬戶。",
        "professional_account_type_3": "您當前的賬戶類型為標準交易賬戶。<br />請知悉，若您滿足所需條件，您可以申請將賬戶升級為專業賬戶。",
        "account_type_difference_title": "專業賬⼾與標準賬⼾有何不同?",
        "professional_account_table_title_1": "最⾼杠桿及其他賬⼾項⽬",
        "standard_account_title": "標準賬⼾<br><span>(直⾄<br>2021年3⽉28⽇)</span>",
        "standard_account_title_2": "標準賬戶<br><span>(自2021年<br>3月29日起適用)</span>",
        "professional_account_title": "專業賬⼾",
        "professional_account_table_forex": "外匯",
        "professional_account_table_indices": "指數",
        "professional_account_table_gold": "黄金",
        "professional_account_table_commodities": "大宗商品（黄金除外）",
        "professional_account_table_share": "股票",
        "professional_account_table_7": "獨家市場分析",
        "professional_account_table_8": "TradingView 專業圖表",
        "professional_account_table_9": "免費財經⽇曆及新聞資訊",
        "professional_account_table_10": "負數額餘保護",
        "professional_account_table_11": "追蹤⽌損功能",
        "professional_account_table_12": "產品披露聲明及⾦融服務指南",
        "professional_account_table_list2_2": "主要貨幣對*<br/>1:30<br />次要貨幣對**<br/>1:20",
        "professional_account_table_list2_3": "主要指數^<br/>1:20<br />次要指數^^<br/>1:10",
        "professional_account_major_currency": "*主要貨幣對：",
        "professional_account_major_currency_desc": "包含以下任何兩個貨幣的貨幣對：澳元、英鎊、加元、歐元、日元、瑞郎及美元",
        "professional_account_ordinary_currency": "**次要貨幣對：",
        "professional_account_ordinary_currency_desc": "任何不是主要貨幣對的貨幣對",
        "professional_account_major_indices": "^主要指數：",
        "professional_account_ordinary_indices": "^^次要指數：",
        "professional_account_major_indices_desc": "法國40指數、德國30指數、美國30指數、歐洲50指數、英國100指數、美國科技股100指數、日本225指數、美國500指數及澳洲200指數",
        "professional_account_ordinaryr_indices_desc": "任何不是主要指數的指數",
        "professional_account_apply_requirements": "Mitrade 專業賬戶申請條件",
        "professional_account_apply_requirements_desc": "您僅需滿足以下兩個條件其中之一，即可申請將標準交易賬戶升級為專業賬戶：",
        "professional_account_apply_requirements_1": "資產：<br />持有最少 <span>250萬澳元</span> 的淨資產*",
        "professional_account_apply_requirements_2": "收⼊：<br />最近兩個財政年中，年度總收⼊不少於 <span>25萬澳元</span>",
        "professional_account_certificate": "您將需要提供相關會計證明**，以證明您已滿足以上的申請資格。請使用我們提供的<a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>會計證明模板</a>.",
        "professional_account_net_asset": "*淨資產：",
        "professional_account_net_asset_desc": "指您所有資產的總價值，包括您的房產、汽車、儲蓄、股票及其他投資。",
        "professional_account_net_asset_desc_2": "**會計證明需由澳洲會計師公會會員（CPA Australia）或澳洲特許會計師協會會員（Chartered Accountants Australia）提供。",
        "professional_account_net_asset_desc_3": "如果您滿足申請專業賬戶的資格，煩請您將相關會計證明發送至 cs@mitrade.com，我們將盡快為您完成剩下的申請手續。",
        "professional_account_faq": "更多疑問>"
    },
    "th": {
        "professional_account_type": "ประเภทบัญชี",
        "professional_account_type_2": "ประเภทบัญชีปัจจุบันของคุณคือบัญชี Mitrade Pro",
        "professional_account_type_3": "ประเภทบัญชีปัจจุบันของคุณคือบัญชีมาตรฐาน <br />โปรดทราบว่าหากคุณมีคุณสมบัติตรงตามข้อกำหนดสำหรับ Mitrade Pro คุณสามารถอัปเกรดบัญชีของคุณเป็นบัญชี Mitrade Pro ได้",
        "account_type_difference_title": "Mitrade Pro VS บัญชีมาตรฐานของเรา",
        "professional_account_table_title_1": "เลเวอเรจ (สูงสุด) และข้อมูลจำเพาะของบัญชีอื่น ๆ",
        "standard_account_title": "บัญชีมาตรฐาน <br><span>(ถึงวันที่ 28 มี.ค. 2564)</span>",
        "standard_account_title_2": "บัญชีมาตรฐาน<br><span>(ตั้งแต่วันที่ 29 มี.ค. 2564 เป็นต้นไป)</span>",
        "professional_account_title": "Mitrade Pro ",
        "professional_account_table_forex": "ฟอเร็กซ์",
        "professional_account_table_indices": "ดัชนี",
        "professional_account_table_gold": "ทองคำ",
        "professional_account_table_commodities": "สินค้าโภคภัณฑ์ (นอกเหนือจากทองคำ)",
        "professional_account_table_share": "หุ้น",
        "professional_account_table_7": "การวิเคราะห์ตลาดแบบพิเศษ",
        "professional_account_table_8": "แผนภูมิ TradingView ระดับมืออาชีพ",
        "professional_account_table_9": "รับปฏิทินเศรษฐกิจและข่าวฟรี",
        "professional_account_table_10": "การป้องกันยอดคงเหลือติดลบ",
        "professional_account_table_11": "Trailing Stop Loss",
        "professional_account_table_12": "คำชี้แจงการเปิดเผยข้อมูลผลิตภัณฑ์ & คู่มือบริการทางการเงิน",
        "professional_account_table_list2_2": "คู่เงินหลัก*<br/>1:30<br />คู่เงินรอง**<br/>1:20",
        "professional_account_table_list2_3": "ดัชนีหลัก^<br/>1:20<br />ดัชนีรอง^^<br/>1:10",
        "professional_account_major_currency": "*คู่เงินหลัก:",
        "professional_account_major_currency_desc": "คู่สกุลเงินที่ประกอบด้วย: AUD, GBP, CAD, EUR, JPY, CHF และ USD",
        "professional_account_ordinary_currency": "**คู่เงินรอง:",
        "professional_account_ordinary_currency_desc": "คู่เงินใด ๆ ที่ไม่ใช่คู่เงินหลัก",
        "professional_account_major_indices": "^ดัชนีหลัก:",
        "professional_account_ordinary_indices": "^^ดัชนีรอง:",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 และ AUS200",
        "professional_account_ordinaryr_indices_desc": "ดัชนีหุ้นที่ไม่ใช่ดัชนีหุ้นหลัก",
        "professional_account_apply_requirements": "จะสมัคร Mitrade Pro ได้อย่างไร?",
        "professional_account_apply_requirements_desc": "เมื่อปฏิบัติตามเงื่อนไขข้อใดข้อหนึ่งด้านล่างนี้แสดงว่าคุณมีคุณสมบัติในการสมัคร Mitrade Pro:",
        "professional_account_apply_requirements_1": "สินทรัพย์: <br />มีทรัพย์สินสุทธิ* อย่างน้อย <span>2.5 ล้านเหรียญออสเตรเลีย</span>",
        "professional_account_apply_requirements_2": "รายได้: <br />รายได้รวมในช่วงสองปีการเงินที่ผ่านมาเป็นอย่างน้อย<span> 250,000 เหรียญออสเตรเลีย</span>",
        "professional_account_certificate": "คุณจะต้องจัดหาใบรับรองการบัญชี** เพื่อพิสูจน์ว่าคุณมีคุณสมบัติตรงตามเกณฑ์ข้างต้น เทมเพลตสำหรับใบรับรองการบัญชีสามารถพบได้ <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>ที่นี่</a>.",
        "professional_account_net_asset": "*ทรัพย์สินสุทธิ",
        "professional_account_net_asset_desc": "อ้างถึงมูลค่ารวมของทรัพย์สิน เช่น ทรัพย์สิน รถยนต์ เงินออม หุ้น และการลงทุนอื่น ๆ",
        "professional_account_net_asset_desc_2": "**ใบรับรองบัญชีต้องจัดทำโดยสมาชิกของ CPA Australia/Chartered Accountants Australia",
        "professional_account_net_asset_desc_3": "หากคุณมีคุณสมบัติสำหรับ Mitrade Pro โปรดส่งใบรับรองบัญชีของคุณมาที่ cs@mitrade.com แล้วเราจะดูแลส่วนที่เหลือให้คุณ",
        "professional_account_faq": "คำถามเพิ่มเติม>"
    },
    "vn": {
        "professional_account_type": "Các loại tài khoản",
        "professional_account_type_2": "Loại tài khoản hiện tại của bạn là tài khoản Chuyên nghiệp.",
        "professional_account_type_3": "Loại tài khoản hiện tại của bạn là tài khoản Tiêu chuẩn. <br />Xin lưu ý, nếu bạn đáp ứng các yêu cầu của Mitrade Pro, bạn có thể nâng cấp tài khoản của mình lên thành tài khoản Chuyên nghiệp.",
        "account_type_difference_title": "Tài khoản Mitrade Pro và tài khoản thường?",
        "professional_account_table_title_1": "Đòn bẩy cao nhất và nhiều mục chọn khác",
        "standard_account_title": "Tài khoản thường<br><span>(Sử dụng đến ngày 28 tháng 3 năm 2021)</span>",
        "standard_account_title_2": "Tài khoản thường<br><span>(Từ ngày 29 tháng 3 năm 2021)</span>",
        "professional_account_title": "Mitrade Pro",
        "professional_account_table_forex": "Ngoại hối",
        "professional_account_table_indices": "Chỉ số",
        "professional_account_table_gold": "Vàng",
        "professional_account_table_commodities": "Hàng hoá (trừ Vang)",
        "professional_account_table_share": "Cổ phiếu",
        "professional_account_table_7": "Phân tích thị trường độc quyền ",
        "professional_account_table_8": "Biểu đồ của TradingView",
        "professional_account_table_9": "Lịch kinh tế & Tin tức Miễn phí",
        "professional_account_table_10": "Bảo vệ số dư âm",
        "professional_account_table_11": "Chức năng theo dõi lỗ ",
        "professional_account_table_12": "Tuyên bố Sản phẩm và Hướng dẫn Dịch vụ Tài chính",
        "professional_account_table_list2_2": "Các cặp tiền tệ chính *<br/>1:30<br />Các cặp tiền phụ **<br/>1:20",
        "professional_account_table_list2_3": "Chỉ số chính ^<br/>1:20<br />Chỉ số phụ ^^<br/>1:10",
        "professional_account_major_currency": "*Các cặp tiền tệ chính:",
        "professional_account_major_currency_desc": "AUD, GBP, CAD, EUR, JPY, CHF và USD",
        "professional_account_ordinary_currency": "**Các cặp tiền phụ:",
        "professional_account_ordinary_currency_desc": "các cặp còn lại",
        "professional_account_major_indices": "^Chỉ số chính:",
        "professional_account_ordinary_indices": "^^Chỉ số phụ: ",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 và AUS200",
        "professional_account_ordinaryr_indices_desc": "các cặp còn lại",
        "professional_account_apply_requirements": "Làm thế nào để đăng ký tài khoản Mitrade Pro?",
        "professional_account_apply_requirements_desc": "Bạn chỉ cần đáp ứng một trong những điều kiện sau là có thể đăng ký tài khoản Mitrade Pro:",
        "professional_account_apply_requirements_1": "Tài sản: <br />nắm giữ ít nhất <span>2,5 triệu đô la Úc</span> trong tài sản ròng *",
        "professional_account_apply_requirements_2": "Thu nhập: <br />Trong 2 năm gần nhất, tổng thu nhập hàng năm không dưới <span>250.000 đô la Úc</span>",
        "professional_account_certificate": "Bạn sẽ cần cung cấp chứng chỉ kế toán ** để chứng minh rằng bạn đã đáp ứng các tiêu chí trên. Mẫu chứng chỉ kế toán có thể được tìm thấy tại <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>đây</a>.",
        "professional_account_net_asset": "*Tài sản ròng",
        "professional_account_net_asset_desc": "Tham khảo tổng giá trị tài sản như tài sản, xe hơi, tiền tiết kiệm, cổ phiếu và các khoản đầu tư khác của bạn.",
        "professional_account_net_asset_desc_2": "**Chứng chỉ kế toán phải được cấp bởi một thành viên của CPA Australia/Chartered Accountants Australia.",
        "professional_account_net_asset_desc_3": "Nếu bạn đủ điều kiện tham gia Mitrade Pro, vui lòng gửi chứng nhận kế toán của bạn đến cs@mitrade.com và chúng tôi sẽ lo phần còn lại cho bạn.",
        "professional_account_faq": "Các câu hỏi khác >"
    },
    "kr": {
        "professional_account_type": "계정 유형",
        "professional_account_type_2": "현재 계정 유형은 프로페셔널 계정입니다.",
        "professional_account_type_3": "현재 계정 유형은 표준 계정입니다. <br />Mitrade Pro의 요구 사항을 충족할 경우 계정을 프로페셔널 계정으로 업그레이드할 수 있습니다.",
        "account_type_difference_title": "Mitrade Pro VS 표준 계정",
        "professional_account_table_title_1": "레버리지(최대) 및 기타 계정 사양",
        "standard_account_title": "표준 계정<br><span>(2021년3월28일 까지)</span>",
        "standard_account_title_2": "표준 계정<br><span>(2021년3월28일 부터)</span>",
        "professional_account_title": "Mitrade Pro",
        "professional_account_table_forex": "외환",
        "professional_account_table_indices": "주가지수",
        "professional_account_table_gold": "금",
        "professional_account_table_commodities": "원자재 (금 제외)",
        "professional_account_table_share": "주식",
        "professional_account_table_7": "독점적인 시장 분석",
        "professional_account_table_8": "전문적인 TradeView 차트",
        "professional_account_table_9": "무료 경제 달력 & 뉴스",
        "professional_account_table_10": "마이너스 잔액 보호 기능",
        "professional_account_table_11": "추적 손실 제한",
        "professional_account_table_12": "상품 공시 & 금융 서비스 안내",
        "professional_account_table_list2_2": "주요한 외환쌍*<br/>1:30<br />마이너 외환쌍**<br/>1:20",
        "professional_account_table_list2_3": "주요한 주가지수^<br/>1:20<br />마이너 주가지수^^<br/>1:10",
        "professional_account_major_currency": "*주요한 외환쌍: ",
        "professional_account_major_currency_desc": "AUD, GBP, CAD, EUR, JPY, CHF 및 USD의 두 가지 중 하나로 구성된 통화 쌍",
        "professional_account_ordinary_currency": "**마이너 외환쌍: ",
        "professional_account_ordinary_currency_desc": "주요 외환쌍이 아닌 모든 외환 쌍",
        "professional_account_major_indices": "^주요한 주가지수: ",
        "professional_account_ordinary_indices": "^^마이너 주가지수: ",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 및 AUS200",
        "professional_account_ordinaryr_indices_desc": "주요한 주가지수가 아닌 모든 주가지수",
        "professional_account_apply_requirements": "Mitrade Pro를 신청하려면 어떻게 해야<br>하나요?",
        "professional_account_apply_requirements_desc": "아래 조건 중 하나를 충족하면 Mitrade Pro에 신청할 수 있습니다.",
        "professional_account_apply_requirements_1": "자산: <br />순 자산*이 최소 <span>250만 호주달러</span> 이 있습니다.",
        "professional_account_apply_requirements_2": "소득: <br />최근 2년 동안의 각 총소득은 최소한<span>$25만 호주달러</span> 입니다.",
        "professional_account_certificate": "위의 기준을 충족했음을 증명하려면 회계사 증면서**을 제공해야 합니다. 회계사 증면서의 템플릿은 <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>여기</a>에서 찾을 수 있습니다.",
        "professional_account_net_asset": "*순자산",
        "professional_account_net_asset_desc": "자산 총 가치(예: 재산, 자동차, 저축, 주식 및 기타 투자)",
        "professional_account_net_asset_desc_2": "**회계 증명서는 CPA 호주/ 호주 공인 회계사 회원이 작성해야 합니다.",
        "professional_account_net_asset_desc_3": "만약 고객님이 Mitrade Pro의 자격이 있다면, cs@mitrade.com 으로 고객님의 회계 증명서를 보내주시면, 저희가 나머지를 처리할겠습니다.",
        "professional_account_faq": "추가 질문 >"    
    },
    "id": {
        "professional_account_type": "Jenis akun",
        "professional_account_type_2": "Jenis akun anda sekarang adalah akun profesional.",
        "professional_account_type_3": "Jenis akun anda sekarang adalah akun standar. <br />Harap ingat bahwa jika Anda memenuhi syarat akun Pro Mitrade, anda dapat tingkatkan akun anda ke akun profesional.  ",
        "account_type_difference_title": "Akun Pro Mitrade VS Akun Standar",
        "professional_account_table_title_1": "Leverage (hingga) dan spesifikasi akun lainnya.",
        "standard_account_title": "Akun Standar<br><span>(Hingga 28 Maret 2021)</span>",
        "standard_account_title_2": "Akun Standar<br><span>(Mulai 29 Maret 2021)</span>",
        "professional_account_title": "Akun Pro Mitrade",
        "professional_account_table_forex": "Forex",
        "professional_account_table_indices": "Indeks",
        "professional_account_table_gold": "Emas",
        "professional_account_table_commodities": "Komoditas (selain emas)",
        "professional_account_table_share": "Saham",
        "professional_account_table_7": "Analisis Pasar Eksklusif",
        "professional_account_table_8": "Grafik TradingView Profesional",
        "professional_account_table_9": "Kalender Ekonomi & Berita Gratis",
        "professional_account_table_10": "Perlindungan Saldo Negatif",
        "professional_account_table_11": "Trailing Stop Loss",
        "professional_account_table_12": "Pernyataan Pengungkapan Produk & Panduan Layanan Keuangan",
        "professional_account_table_list2_2": "Pasangan Mata Uang Mayor*<br/>1:30<br />Pasangan Mata Uang Minor**<br/>1:20",
        "professional_account_table_list2_3": "Indeks Mayor^<br/>1:20<br />Indeks Minor^^<br/>1:10",
        "professional_account_major_currency": "*Pasangan Mata Uang Mayor: ",
        "professional_account_major_currency_desc": "pasangan mata uang yang terdiri dari dua mata uang berikut: AUD, GBP, CAD, EUR, JPY, CHF dan USD",
        "professional_account_ordinary_currency": "**Pasangan Mata Uang Minor: ",
        "professional_account_ordinary_currency_desc": "pasangan mana pun yang bukan Pasangan Mata Uang Mayor",
        "professional_account_major_indices": "^Indeks Mayor: ",
        "professional_account_ordinary_indices": "^^Indeks Minor: ",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 dan AUS200",
        "professional_account_ordinaryr_indices_desc": "indeks pasar saham yang bukan merupakan indeks mayor.",
        "professional_account_apply_requirements": "Bagaimana cara ajukan Akun Pro Mitrade",
        "professional_account_apply_requirements_desc": "Anda dapat mengajukan akun pro Mitrade cukup memenuhi salah satu persyaratan sebagai berikutnya:",
        "professional_account_apply_requirements_1": "Aset: <br />Memiliki aset bersih * minimal <span>AU$ 2,5 juta</span>",
        "professional_account_apply_requirements_2": "Pendapatan: <br />Pendapatan kotor untuk dua tahun keuangan terakhir tidak kurang dari<span> AU$ 250.000</span>",
        "professional_account_certificate": "Anda harus menyediakan sertifikat akuntansi ** untuk membuktikan bahwa Anda telah memenuhi kriteria tersebut. Template untuk sertifikat akuntansi dapat ditemukan <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>di sini</a>.",
        "professional_account_net_asset": "*Aset bersih",
        "professional_account_net_asset_desc": "Mengacu pada nilai total aset misalnya properti, mobil, tabungan, saham, dan investasi lainnya.",
        "professional_account_net_asset_desc_2": "**Sertifikat akuntansi harus disediakan oleh anggota CPA Australia/Chartered Accountants Australia.",
        "professional_account_net_asset_desc_3": "Jika Anda memenuhi syarat untuk tingkatkan ke Mitrade Pro, silahkan kirimkan sertifikasi akuntansi Anda ke cs@mitrade.com dan kami akan menyelesaikan prosedur yang sisanya.",
        "professional_account_faq": "Pertanyaan a lain>"
    },
    "my": {
        "professional_account_type": "Jenis akaun",
        "professional_account_type_2": "Jenis akaun semasa anda adalah akaun profesional.",
        "professional_account_type_3": "Jenis akaun semasa anda adalah akaun biasa. <br />Harap perhatikan, jika anda memenuhi syarat untuk Mitrade Pro, anda boleh meningkatkan akaun anda menjadi akaun profesional.",
        "account_type_difference_title": "Akaun Pro Mitrade VS Akaun Standar",
        "professional_account_table_title_1": "Leverage (hingga) dan spesifikasi akaun lain.",
        "standard_account_title": "Akaun Standard<br><span>(Sehingga 28 Mac 2021)</span>",
        "standard_account_title_2": "Akaun Standard<br><span>(Dari 29 Mac 2021 dan seterusnya)</span>",
        "professional_account_title": "Akaun Pro Mitrade",
        "professional_account_table_forex": "Forex",
        "professional_account_table_indices": "Indeks",
        "professional_account_table_gold": "Emas",
        "professional_account_table_commodities": "Komoditi (selain emas)",
        "professional_account_table_share": "Saham",
        "professional_account_table_7": "Analisis Pasaran Eksklusif",
        "professional_account_table_8": "Carta Paparan Perdagangan Profesional",
        "professional_account_table_9": "Kalendar & Berita Ekonomi Percuma",
        "professional_account_table_10": "Perlindungan Imbangan Negatif",
        "professional_account_table_11": "Trailing Stop Loss",
        "professional_account_table_12": "Penyataan Pendedahan Produk & Panduan Perkhidmatan Kewangan",
        "professional_account_table_list2_2": "Pasangan Major*<br/>1:30<br />Pasangan Minor**<br/>1:20",
        "professional_account_table_list2_3": "Indeks Major^<br/>1:20<br />Indeks Minor^^<br/>1:10",
        "professional_account_major_currency": "*Pasangan Major: ",
        "professional_account_major_currency_desc": "sepasang mata wang yang terdiri daripada dua perkara berikut: AUD, GBP, CAD, EUR, JPY, CHF dan USD",
        "professional_account_ordinary_currency": "**Pasangan Minor: ",
        "professional_account_ordinary_currency_desc": "mana-mana pasangan yang bukan Pasangan Utama",
        "professional_account_major_indices": "^Indeks Major: ",
        "professional_account_ordinary_indices": "^^Indeks Minor: ",
        "professional_account_major_indices_desc": "FR40, GER30, US30, EU50, UK100, NAS100, JPN225, US500 dan AUS200",
        "professional_account_ordinaryr_indices_desc": "indeks pasaran saham yang bukan merupakan indeks pasaran saham utama.",
        "professional_account_apply_requirements": "Bagaimana Memohon Akaun Pro Mitrade?",
        "professional_account_apply_requirements_desc": "Dengan memenuhi salah satu syarat di bawah ini, anda layak untuk memohon Mitrade Pro:",
        "professional_account_apply_requirements_1": "Aset: <br />Mempunyai aset bersih * sekurang-kurangnya <span>AU $ 2.5 juta</span>.",
        "professional_account_apply_requirements_2": "Pendapatan: <br />Pendapatan kasar untuk setiap dua tahun kewangan terakhir adalah sekurang-kurangnya <span>$250,000</span>.",
        "professional_account_certificate": "Anda perlu memberikan sijil perakaunan ** untuk membuktikan bahawa anda telah memenuhi kriteria di atas. Templat untuk sijil perakaunan boleh didapati <a href='https://www.mitrade.com/uploads/doc/Mitrade_CertificateByQualifiedAccountant-en-US.pdf'>di sini</a>.",
        "professional_account_net_asset": "*Aset bersih",
        "professional_account_net_asset_desc": "Rujuk jumlah nilai aset seperti harta tanah, kereta, simpanan, saham dan pelaburan lain.",
        "professional_account_net_asset_desc_2": "**Sijil perakaunan mesti disediakan oleh anggota CPA Australia/Chartered Accountants Australia.",
        "professional_account_net_asset_desc_3": "Sekiranya anda layak untuk Mitrade Pro, sila kirimkan sijil perakaunan anda ke cs@mitrade.com dan kami akan menguruskan selebihnya untuk anda.",
        "professional_account_faq": "Pertanyaan yang lain>"
    }
}